/* The following code was generated by JFlex 1.7.0 */

import java.util.Stack;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexer.jflex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int INCOMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\5\1\6\1\6\1\4\22\0\1\2\1\22\4\0"+
    "\1\25\1\0\1\14\1\15\1\20\1\17\1\0\1\16\1\0\1\21"+
    "\1\10\7\1\1\11\1\1\1\0\1\13\1\34\1\35\1\33\2\0"+
    "\1\26\1\3\1\51\1\46\1\23\1\40\2\3\1\56\2\3\1\64"+
    "\1\3\1\45\1\31\1\3\1\61\1\3\1\54\1\36\2\3\1\62"+
    "\3\3\6\0\1\41\1\3\1\52\1\30\1\37\1\47\1\3\1\53"+
    "\1\55\2\3\1\42\1\3\1\27\1\57\2\3\1\32\1\43\1\24"+
    "\1\7\1\65\1\44\1\3\1\50\1\3\1\60\1\0\1\63\7\0"+
    "\1\12\u1fa2\0\1\6\1\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\2\5\1\4\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\4"+
    "\1\1\4\4\1\16\1\17\1\20\5\4\1\21\1\4"+
    "\1\22\1\4\1\3\3\23\1\0\1\24\1\3\1\25"+
    "\1\26\3\4\1\26\5\4\1\27\7\4\2\30\2\4"+
    "\1\31\1\32\1\0\1\22\4\4\1\33\1\34\11\4"+
    "\1\35\3\4\1\36\1\4\1\21\5\4\1\37\3\4"+
    "\1\40\1\41\1\42\1\43\1\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\154\0\330\0\u010e\0\u0144"+
    "\0\u017a\0\154\0\154\0\154\0\154\0\154\0\154\0\u01b0"+
    "\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a\0\154"+
    "\0\154\0\154\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\154"+
    "\0\u046e\0\154\0\u04a4\0\u04da\0\u0510\0\u0144\0\154\0\u0546"+
    "\0\154\0\u057c\0\154\0\330\0\u05b2\0\u05e8\0\u061e\0\154"+
    "\0\u0654\0\u068a\0\u06c0\0\u06f6\0\u072c\0\330\0\u0762\0\u0798"+
    "\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\330\0\u0912"+
    "\0\u0948\0\154\0\154\0\u097e\0\330\0\u09b4\0\u09ea\0\u0a20"+
    "\0\u0a56\0\330\0\330\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64"+
    "\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\330\0\u0c72\0\u0ca8\0\u0cde"+
    "\0\330\0\u0d14\0\330\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u0e22"+
    "\0\330\0\u0e58\0\u0e8e\0\u0ec4\0\330\0\330\0\330\0\330"+
    "\0\u0efa";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\2\10\1\11\2\4"+
    "\1\3\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\6\1\23\1\24\1\25\1\26\1\27"+
    "\1\6\1\30\1\31\1\32\1\33\1\6\1\34\4\6"+
    "\1\25\1\26\2\6\1\35\2\6\1\36\1\6\1\37"+
    "\1\6\1\40\1\6\1\41\1\42\1\43\1\6\20\5"+
    "\1\44\45\5\67\0\1\4\6\0\2\4\57\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\22\6"+
    "\1\0\2\6\1\0\2\6\2\0\1\10\1\0\1\45"+
    "\1\46\1\47\3\0\1\47\55\0\1\10\1\0\1\45"+
    "\2\47\3\0\1\47\56\0\1\6\3\0\1\6\1\50"+
    "\12\0\2\6\1\0\5\6\3\0\22\6\1\0\2\6"+
    "\1\0\2\6\20\0\1\51\1\52\101\0\1\53\33\0"+
    "\1\6\3\0\1\6\13\0\1\6\1\54\1\0\1\6"+
    "\1\55\3\6\3\0\4\6\1\56\7\6\1\57\5\6"+
    "\1\0\2\6\1\0\2\6\25\0\1\60\43\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\1\6\1\61\3\6"+
    "\3\0\4\6\1\62\15\6\1\0\2\6\1\0\1\6"+
    "\1\63\3\0\1\6\3\0\1\6\13\0\2\6\1\0"+
    "\5\6\3\0\1\6\1\64\20\6\1\0\2\6\1\0"+
    "\2\6\3\0\1\6\3\0\1\6\13\0\2\6\1\0"+
    "\5\6\3\0\1\6\1\65\20\6\1\0\2\6\1\0"+
    "\2\6\3\0\1\6\3\0\1\66\13\0\2\6\1\0"+
    "\4\6\1\66\3\0\22\6\1\0\2\6\1\0\2\6"+
    "\3\0\1\6\3\0\1\6\13\0\2\6\1\0\4\6"+
    "\1\67\3\0\3\6\1\70\11\6\1\71\3\6\1\72"+
    "\1\0\2\6\1\0\2\6\3\0\1\6\3\0\1\6"+
    "\13\0\2\6\1\0\5\6\3\0\3\6\1\73\13\6"+
    "\1\74\2\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\3\6"+
    "\1\75\16\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\17\6"+
    "\1\76\2\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\11\6"+
    "\1\77\10\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\15\6"+
    "\1\100\4\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\17\6"+
    "\1\101\2\6\1\0\2\6\1\0\2\6\21\0\1\102"+
    "\51\0\1\103\70\0\1\104\55\0\5\52\1\0\60\52"+
    "\3\0\1\6\3\0\1\6\13\0\2\6\1\0\2\6"+
    "\1\105\2\6\3\0\22\6\1\0\2\6\1\0\2\6"+
    "\3\0\1\6\3\0\1\6\13\0\2\6\1\0\5\6"+
    "\3\0\5\6\1\106\14\6\1\0\2\6\1\0\2\6"+
    "\3\0\1\6\3\0\1\6\13\0\2\6\1\0\4\6"+
    "\1\107\3\0\22\6\1\0\2\6\1\0\2\6\3\0"+
    "\1\6\3\0\1\6\13\0\2\6\1\0\2\6\1\54"+
    "\2\6\3\0\22\6\1\0\2\6\1\0\2\6\3\0"+
    "\1\6\3\0\1\6\13\0\2\6\1\0\5\6\3\0"+
    "\21\6\1\110\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\3\6"+
    "\1\111\16\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\6\6"+
    "\1\112\13\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\11\6"+
    "\1\113\10\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\114\13\0\2\6\1\0\5\6\3\0\12\6"+
    "\1\113\7\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\1\6\1\115\3\6"+
    "\3\0\22\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\1\6"+
    "\1\116\20\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\117\13\0\2\6\1\0\5\6\3\0\22\6"+
    "\1\0\2\6\1\0\2\6\3\0\1\6\3\0\1\6"+
    "\13\0\2\6\1\0\5\6\3\0\4\6\1\120\15\6"+
    "\1\0\2\6\1\0\2\6\3\0\1\6\3\0\1\6"+
    "\13\0\2\6\1\0\1\6\1\105\3\6\3\0\22\6"+
    "\1\0\2\6\1\0\2\6\3\0\1\6\3\0\1\6"+
    "\13\0\1\6\1\121\1\0\5\6\3\0\22\6\1\0"+
    "\2\6\1\0\2\6\3\0\1\6\3\0\1\6\13\0"+
    "\2\6\1\0\1\6\1\122\3\6\3\0\22\6\1\0"+
    "\2\6\1\0\2\6\3\0\1\6\3\0\1\6\13\0"+
    "\2\6\1\0\5\6\3\0\17\6\1\123\2\6\1\0"+
    "\2\6\1\0\2\6\3\0\1\6\3\0\1\6\13\0"+
    "\2\6\1\0\4\6\1\124\3\0\22\6\1\0\2\6"+
    "\1\0\2\6\11\0\1\10\57\0\1\6\3\0\1\6"+
    "\13\0\2\6\1\0\5\6\3\0\1\6\1\125\20\6"+
    "\1\0\2\6\1\0\2\6\3\0\1\6\3\0\1\6"+
    "\13\0\2\6\1\0\5\6\3\0\17\6\1\126\2\6"+
    "\1\0\2\6\1\0\2\6\3\0\1\6\3\0\1\6"+
    "\13\0\2\6\1\0\4\6\1\127\3\0\22\6\1\0"+
    "\2\6\1\0\2\6\3\0\1\6\3\0\1\6\13\0"+
    "\2\6\1\0\1\6\1\130\3\6\3\0\22\6\1\0"+
    "\2\6\1\0\2\6\3\0\1\6\3\0\1\6\13\0"+
    "\2\6\1\0\5\6\3\0\1\6\1\131\20\6\1\0"+
    "\2\6\1\0\2\6\3\0\1\6\3\0\1\6\13\0"+
    "\1\6\1\132\1\0\5\6\3\0\22\6\1\0\2\6"+
    "\1\0\2\6\3\0\1\6\3\0\1\6\13\0\2\6"+
    "\1\0\1\6\1\133\3\6\3\0\22\6\1\0\2\6"+
    "\1\0\2\6\3\0\1\6\3\0\1\6\13\0\2\6"+
    "\1\0\4\6\1\134\3\0\22\6\1\0\2\6\1\0"+
    "\2\6\3\0\1\6\3\0\1\6\13\0\2\6\1\0"+
    "\5\6\3\0\5\6\1\135\14\6\1\0\2\6\1\0"+
    "\2\6\3\0\1\6\3\0\1\6\13\0\2\6\1\0"+
    "\5\6\3\0\14\6\1\136\5\6\1\0\2\6\1\0"+
    "\2\6\3\0\1\6\3\0\1\6\13\0\2\6\1\0"+
    "\5\6\3\0\21\6\1\137\1\0\2\6\1\0\2\6"+
    "\3\0\1\6\3\0\1\6\13\0\2\6\1\0\5\6"+
    "\3\0\4\6\1\140\15\6\1\0\2\6\1\0\2\6"+
    "\3\0\1\6\3\0\1\6\13\0\2\6\1\0\5\6"+
    "\3\0\1\6\1\141\20\6\1\0\2\6\1\0\2\6"+
    "\3\0\1\6\3\0\1\6\13\0\2\6\1\0\4\6"+
    "\1\142\3\0\22\6\1\0\2\6\1\0\2\6\3\0"+
    "\1\6\3\0\1\6\13\0\2\6\1\0\5\6\3\0"+
    "\5\6\1\133\14\6\1\0\2\6\1\0\2\6\3\0"+
    "\1\6\3\0\1\6\13\0\2\6\1\0\5\6\3\0"+
    "\14\6\1\143\5\6\1\0\2\6\1\0\2\6\3\0"+
    "\1\6\3\0\1\6\13\0\2\6\1\0\5\6\3\0"+
    "\22\6\1\0\1\144\1\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\1\6\1\143\3\6"+
    "\3\0\22\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\1\6"+
    "\1\145\20\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\15\6"+
    "\1\146\4\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\1\6\1\125\3\6"+
    "\3\0\22\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\1\6"+
    "\1\147\20\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\1\6"+
    "\1\150\20\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\6\13\0\2\6\1\0\5\6\3\0\1\6"+
    "\1\151\20\6\1\0\2\6\1\0\2\6\3\0\1\6"+
    "\3\0\1\140\13\0\2\6\1\0\5\6\3\0\22\6"+
    "\1\0\2\6\1\0\2\6\3\0\1\6\3\0\1\6"+
    "\13\0\2\6\1\0\4\6\1\150\3\0\22\6\1\0"+
    "\2\6\1\0\2\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3888];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\4\1\6\11\10\1\3\11"+
    "\5\1\1\11\1\1\1\11\4\1\1\11\1\0\1\11"+
    "\1\1\1\11\4\1\1\11\21\1\2\11\1\0\45\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	public int getColumn() {return yycolumn + 1;}
	public int getLine() {return yyline + 1;}
	public int getChar() {return yychar + 1;}
	private Stack<Integer> stackSpace = new Stack<>();
	private boolean isNewLine = true;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
  	stackSpace.add(0);
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 202) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException, java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              int nbspace = 0;
																while (!stackSpace.empty()) {
																		nbspace++;
																		stackSpace.pop();
																}
																return new Token(TokenKind.EOF, nbspace + 1);
            }  // fall though
            case 106: break;
            case INCOMMENT: {
              int nbspace = 0;
																while (!stackSpace.empty()) {
																	nbspace++;
																	stackSpace.pop();
																}
																return new Token(TokenKind.EOF, nbspace + 1);
            }  // fall though
            case 107: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new java.io.IOException("Symbole non reconnu (" + yytext() + ") Line " + getLine() + " Column " + getColumn() + " Char " + getChar());
            } 
            // fall through
          case 36: break;
          case 2: 
            { isNewLine = false; return new IntToken(TokenKind.INT, Integer.parseInt(yytext()));
            } 
            // fall through
          case 37: break;
          case 3: 
            { 
            } 
            // fall through
          case 38: break;
          case 4: 
            { isNewLine = false; return new StringToken(TokenKind.VAR, yytext());
            } 
            // fall through
          case 39: break;
          case 5: 
            { if (isNewLine) {
																	int nbspace = 0;
																	for (int i = 1; i < yytext().length(); i++) {
																		if (yytext().charAt(i) == ' ')
																			nbspace++;
																		else if (yytext().charAt(i) == '\t')
																			nbspace = nbspace + 4;
																	}
																	if (stackSpace.empty() || stackSpace.peek() < nbspace) {
																		stackSpace.push(nbspace);
																		return new Token(TokenKind.OPEN);
																	} else if (nbspace != stackSpace.peek()) {
																		int nbSpace = 0;
																		while (!stackSpace.empty() && stackSpace.peek() > nbspace) {
																			nbSpace++;
																			stackSpace.pop();
																		}
																		if (stackSpace.empty() || stackSpace.peek() < nbspace)
																			throw new java.io.IOException("Mauvaise Indentation Ligne " + (getLine() + 1));
																		else
																			return new Token(TokenKind.CLOSE, nbSpace);
																	}
																}
            } 
            // fall through
          case 40: break;
          case 6: 
            { isNewLine = true; return new Token(TokenKind.SEMICOLON);
            } 
            // fall through
          case 41: break;
          case 7: 
            { isNewLine = false; return new Token(TokenKind.LPAR);
            } 
            // fall through
          case 42: break;
          case 8: 
            { isNewLine = false; return new Token(TokenKind.RPAR);
            } 
            // fall through
          case 43: break;
          case 9: 
            { isNewLine = false; return new Token(TokenKind.MINUS);
            } 
            // fall through
          case 44: break;
          case 10: 
            { isNewLine = false; return new Token(TokenKind.PLUS);
            } 
            // fall through
          case 45: break;
          case 11: 
            { isNewLine = false; return new Token(TokenKind.TIMES);
            } 
            // fall through
          case 46: break;
          case 12: 
            { isNewLine = false; return new Token(TokenKind.DIVIDE);
            } 
            // fall through
          case 47: break;
          case 13: 
            { isNewLine = false; return new Token(TokenKind.NOT);
            } 
            // fall through
          case 48: break;
          case 14: 
            { isNewLine = false; return new Token(TokenKind.SUP);
            } 
            // fall through
          case 49: break;
          case 15: 
            { isNewLine = false; return new Token(TokenKind.INF);
            } 
            // fall through
          case 50: break;
          case 16: 
            { isNewLine = false; return new Token(TokenKind.EQ);
            } 
            // fall through
          case 51: break;
          case 17: 
            { isNewLine = true; return new Token(TokenKind.THEN);
            } 
            // fall through
          case 52: break;
          case 18: 
            { isNewLine = true; return new Token(TokenKind.END);
            } 
            // fall through
          case 53: break;
          case 19: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { 
            } 
            // fall through
          case 54: break;
          case 20: 
            { yybegin(INCOMMENT);
            } 
            // fall through
          case 55: break;
          case 21: 
            { isNewLine = false; return new Token(TokenKind.NOTEQ);
            } 
            // fall through
          case 56: break;
          case 22: 
            { isNewLine = false; return new Token(TokenKind.AND);
            } 
            // fall through
          case 57: break;
          case 23: 
            { isNewLine = false; return new Token(TokenKind.OR);
            } 
            // fall through
          case 58: break;
          case 24: 
            { isNewLine = false; return new Token(TokenKind.IF);
            } 
            // fall through
          case 59: break;
          case 25: 
            { isNewLine = false; yybegin(YYINITIAL);
            } 
            // fall through
          case 60: break;
          case 26: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { 
            } 
            // fall through
          case 61: break;
          case 27: 
            { isNewLine = false; return new Token(TokenKind.NEW);
            } 
            // fall through
          case 62: break;
          case 28: 
            { isNewLine = false; return new Token(TokenKind.DEF);
            } 
            // fall through
          case 63: break;
          case 29: 
            { isNewLine = false; return new Token(TokenKind.ELSE);
            } 
            // fall through
          case 64: break;
          case 30: 
            { isNewLine = false; return new Token(TokenKind.TRUE);
            } 
            // fall through
          case 65: break;
          case 31: 
            { isNewLine = false; return new Token(TokenKind.LIRE);
            } 
            // fall through
          case 66: break;
          case 32: 
            { isNewLine = false; return new Token(TokenKind.FALSE);
            } 
            // fall through
          case 67: break;
          case 33: 
            { isNewLine = false; return new Token(TokenKind.CATCH);
            } 
            // fall through
          case 68: break;
          case 34: 
            { isNewLine = false; return new Token(TokenKind.WHILE);
            } 
            // fall through
          case 69: break;
          case 35: 
            { isNewLine = false; return new StringToken(TokenKind.COM, yytext());
            } 
            // fall through
          case 70: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
